const categorias = {
  despesas: {
    alimentacao: [
      "mercado",
      "supermercado",
      "feira",
      "restaurante",
      "lanche",
      "comida",
      "almoço",
      "jantar",
      "café",
      "padaria",
      "ifood",
      "delivery",
      "açougue",
      "hortifruti",
      "pizza",
      "hamburguer",
      "hamburger",
      "lanchonete",
      "compras",
      "compra",
    ],
    transporte: [
      "gasolina",
      "combustível",
      "combustivel",
      "uber",
      "99",
      "taxi",
      "táxi",
      "ônibus",
      "onibus",
      "metrô",
      "metro",
      "passagem",
      "estacionamento",
      "pedágio",
      "pedagio",
      "carro",
      "moto",
      "manutenção carro",
      "manutencao carro",
      "seguro",
      "ipva",
      "licenciamento",
      "pneu",
      "oficina",
    ],
    moradia: [
      "aluguel",
      "condomínio",
      "condominio",
      "iptu",
      "água",
      "agua",
      "luz",
      "energia",
      "gás",
      "gas",
      "internet",
      "telefone",
      "casa",
      "apartamento",
      "reforma",
      "conserto",
      "manutenção",
      "manutencao",
      "móveis",
      "moveis",
      "decoração",
      "decoracao",
    ],
    conveniencia: [
      "farmácia",
      "farmacia",
      "padaria",
      "lojinha",
      "posto",
      "gasolina",
      "lava-jato",
      "lava jato",
      "correios",
      "correio",
      "lotérica",
      "loteria",
    ],
    saude: [
      "médico",
      "medico",
      "consulta",
      "exame",
      "remédio",
      "remedio",
      "farmácia",
      "farmacia",
      "hospital",
      "plano de saúde",
      "dentista",
      "psicólogo",
      "psicologo",
      "terapia",
      "academia",
      "vitamina",
      "suplemento",
    ],
    educacao: [
      "escola",
      "faculdade",
      "universidade",
      "curso",
      "livro",
      "material",
      "mensalidade",
      "matrícula",
      "matricula",
      "apostila",
      "treinamento",
      "workshop",
      "palestra",
      "certificado",
    ],
    lazer: [
      "cinema",
      "teatro",
      "show",
      "netflix",
      "spotify",
      "prime",
      "disney",
      "hbo",
      "ingresso",
      "viagem",
      "hotel",
      "passeio",
      "bar",
      "balada",
      "festa",
      "shopping",
      "jogos",
      "game",
      "streaming",
    ],
    vestuario: [
      "roupa",
      "camiseta",
      "calça",
      "calca",
      "sapato",
      "tênis",
      "tenis",
      "blusa",
      "vestido",
      "bermuda",
      "shorts",
      "meia",
      "cueca",
      "calcinha",
      "sutiã",
      "sutia",
      "bolsa",
      "mochila",
      "acessório",
      "acessorio",
      "moda",
    ],
    cuidadosPessoais: [
      "cabelo",
      "corte",
      "salão",
      "salao",
      "manicure",
      "pedicure",
      "barbeiro",
      "maquiagem",
      "perfume",
      "creme",
      "shampoo",
      "sabonete",
      "desodorante",
      "academia",
      "spa",
      "massagem",
    ],
    casa: [
      "limpeza",
      "produto",
      "detergente",
      "sabão",
      "sabao",
      "papel higiênico",
      "papel higienico",
      "toalha",
      "roupa de cama",
      "utensílio",
      "utensilio",
      "ferramenta",
      "conserto",
      "reparo",
    ],
    tecnologia: [
      "celular",
      "computador",
      "notebook",
      "tablet",
      "fone",
      "carregador",
      "impressora",
      "software",
      "aplicativo",
      "app",
      "gadget",
      "eletrônico",
      "eletronico",
      "cabo",
      "mouse",
      "teclado",
      "monitor",
    ],
    pets: [
      "ração",
      "racao",
      "pet",
      "veterinário",
      "veterinario",
      "banho",
      "tosa",
      "brinquedo",
      "coleira",
      "vacina",
      "medicamento",
      "petshop",
      "areia",
      "gato",
      "cachorro",
      "animal",
    ],
    investimentos: [
      "investimento",
      "ação",
      "acao",
      "fundo",
      "tesouro",
      "bitcoin",
      "crypto",
      "cripto",
      "poupança",
      "poupanca",
      "cdb",
      "aplicação",
      "aplicacao",
    ],
    outros: [],
  },
  receitas: {
    salario: [
      "salário",
      "salario",
      "salário",
      "salario",
      "13º",
      "13o",
      "13",
      "férias",
      "ferias",
      "ferias",
      "plr",
      "participação",
      "participacao",
      "pagamento",
      "pagamento salário",
      "pagamento salario",
      "hora extra",
      "horaextra",
      "bonus",
      "bônus",
      "adicional",
      "comissão",
      "comissao",
      "adiantamento",
      "adiantamento salário",
      "adiantamento salario",
      "adiantamento 13",
      "adiantamento 13º",
      "adiantamento ferias",
      "adiantamento férias",
    ],
    freelance: [
      "freelance",
      "freela",
      "projeto",
      "consultoria",
      "trabalho",
      "serviço",
      "servico",
      "job",
      "bico",
      "extra",
      "assessoria",
      "mentoria",
      "aula particular",
      "tradução",
      "traducao",
      "design",
      "social media",
      "marketing",
      "desenvolvimento",
      "programação",
      "programacao",
    ],
    investimentos: [
      "dividendo",
      "juros",
      "rendimento",
      "aluguel",
      "aplicação",
      "aplicacao",
      "investimento",
      "ação",
      "acao",
      "fundo",
      "tesouro",
      "bitcoin",
      "crypto",
      "cripto",
      "poupança",
      "poupanca",
      "cdb",
      "dividendos",
      "juros sobre capital",
      "valorização",
      "valorizacao",
      "venda de ações",
      "venda de acoes",
      "resgate",
      "renda fixa",
      "renda variável",
      "renda variavel",
    ],
    vendas: [
      "venda",
      "vendi",
      "comercio",
      "comércio",
      "produto",
      "mercadoria",
      "cliente",
      "revenda",
      "marketplace",
      "loja",
    ],
    presentes: [
      "presente",
      "prêmio",
      "premio",
      "doação",
      "doacao",
      "gift",
      "gratificação",
      "gratificacao",
      "bonificação",
      "bonificacao",
    ],
    reembolsos: [
      "reembolso",
      "restituição",
      "restituicao",
      "devolução",
      "devolucao",
      "cashback",
      "retorno",
      "estorno",
    ],
    outros: [],
  },
};

function detectarCategoriaAutomatica(texto, tipo) {
  const textoLower = texto.toLowerCase();
  const categoriasTipo =
    tipo === "EXPENSE" ? categorias.despesas : categorias.receitas;

  // Primeiro, procurar por correspondências exatas
  for (const [categoria, palavrasChave] of Object.entries(categoriasTipo)) {
    if (palavrasChave.some((palavra) => textoLower.includes(palavra))) {
      return categoria;
    }
  }

  // Se não encontrou correspondência exata, procurar por palavras parciais
  for (const [categoria, palavrasChave] of Object.entries(categoriasTipo)) {
    if (
      palavrasChave.some((palavra) =>
        textoLower
          .split(" ")
          .some((word) => word.length > 3 && palavra.includes(word))
      )
    ) {
      return categoria;
    }
  }

  return "outros";
}

module.exports = {
  categorias,
  detectarCategoriaAutomatica,
};
