version: "3"
services:
  whatsapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./whatsapp-data:/app/whatsapp-data
      - /tmp/chrome-data:/tmp/chrome-data
      - /tmp/whatsapp-data:/tmp/whatsapp-data
    deploy:
      resources:
        limits:
          memory: 300M
    stop_grace_period: 30s
    stop_signal: SIGTERM
    init: true
    restart: always
